# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


class S3KeySensor(BaseSensorOperator):
    bucket_key: "str"
    bucket_name: "typing.Union[str, NoneType]"
    wildcard_match: "bool"
    aws_conn_id: "str"
    verify: "typing.Union[bool, str, NoneType]"
