# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class MsSqlOperator(BaseOperator):
    sql: "str"
    mssql_conn_id: "str"
    parameters: "typing.Union[typing.Mapping, typing.Iterable, NoneType]"
    autocommit: "bool"
    database: "typing.Union[str, NoneType]"
