# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.providers.google.cloud.operators.cloud_base import (
    GoogleCloudBaseOperator,
)


class CreateDataPipelineOperator(GoogleCloudBaseOperator):
    body: "dict"
    project_id: "str | None"
    location: "str"
    gcp_conn_id: "str"
    impersonation_chain: "str | Sequence[str] | None"


class RunDataPipelineOperator(GoogleCloudBaseOperator):
    data_pipeline_name: "str"
    project_id: "str | None"
    location: "str"
    gcp_conn_id: "str"
