# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class CloudTranslateSpeechOperator(BaseOperator):
    audio: "RecognitionAudio"
    config: "RecognitionConfig"
    target_language: "str"
    format_: "str"
    source_language: "typing.Union[str, NoneType]"
    model: "str"
    project_id: "typing.Union[str, NoneType]"
    gcp_conn_id: "str"
    impersonation_chain: "typing.Union[str, typing.Sequence[str], NoneType]"
