# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.operators.branch import BaseBranchOperator


class BranchDateTimeOperator(BaseBranchOperator):
    follow_task_ids_if_true: "typing.Union[str, typing.Iterable[str]]"
    follow_task_ids_if_false: "typing.Union[str, typing.Iterable[str]]"
    target_lower: "typing.Union[datetime.datetime, datetime.time, NoneType]"
    target_upper: "typing.Union[datetime.datetime, datetime.time, NoneType]"
    use_task_execution_date: "bool"
