# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.amazon.aws.transfers.google_api_to_s3 import (
    GoogleApiToS3Operator,
)


@immutable
class GoogleApiToS3Transfer(GoogleApiToS3Operator):
    pass
