# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.apache.druid.transfers.hive_to_druid import (
    HiveToDruidOperator,
)


@immutable
class HiveToDruidTransfer(HiveToDruidOperator):
    pass
