# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.apache.hive.transfers.hive_to_mysql import (
    HiveToMySqlOperator,
)


@immutable
class HiveToMySqlTransfer(HiveToMySqlOperator):
    pass
