# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.apache.hive.transfers.mssql_to_hive import (
    MsSqlToHiveOperator,
)


@immutable
class MsSqlToHiveTransfer(MsSqlToHiveOperator):
    pass
