# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.apache.hive.transfers.mysql_to_hive import (
    MySqlToHiveOperator,
)


@immutable
class MySqlToHiveTransfer(MySqlToHiveOperator):
    pass
