# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.operators.sql import (
    SQLCheckOperator,
    SQLIntervalCheckOperator,
    SQLValueCheckOperator,
)


@immutable
class PrestoCheckOperator(SQLCheckOperator):
    pass


@immutable
class PrestoIntervalCheckOperator(SQLIntervalCheckOperator):
    pass


@immutable
class PrestoValueCheckOperator(SQLValueCheckOperator):
    pass
