# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.mysql.transfers.presto_to_mysql import (
    PrestoToMySqlOperator,
)


@immutable
class PrestoToMySqlTransfer(PrestoToMySqlOperator):
    pass
