# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.apache.hive.transfers.s3_to_hive import (
    S3ToHiveOperator,
)


@immutable
class S3ToHiveTransfer(S3ToHiveOperator):
    pass
