# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.amazon.aws.transfers.s3_to_redshift import (
    S3ToRedshiftOperator,
)


@immutable
class S3ToRedshiftTransfer(S3ToRedshiftOperator):
    pass
