# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.operators.sql import BranchSQLOperator


@immutable
class BranchSqlOperator(BranchSQLOperator):
    pass
