# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.sensors.bigquery import (
    BigQueryTableExistenceSensor,
)


@immutable
class BigQueryTableSensor(BigQueryTableExistenceSensor):
    pass
