# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.apache.hdfs.sensors.hdfs import (
    HdfsFolderSensor,
    HdfsRegexSensor,
)


@immutable
class HdfsSensorFolder(HdfsFolderSensor):
    pass


@immutable
class HdfsSensorRegex(HdfsRegexSensor):
    pass
