# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.decorators.python import _PythonDecoratedOperator
from airfly._vendor.airflow.operators.python import BranchPythonVirtualenvOperator


class _BranchPythonVirtualenvDecoratedOperator(
    _PythonDecoratedOperator,
    BranchPythonVirtualenvOperator,
):
    python_callable: "_empty"
    op_args: "_empty"
    op_kwargs: "_empty"
