# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.decorators.base import DecoratedOperator
from airfly._vendor.airflow.operators.python import PythonVirtualenvOperator


@immutable
class _PythonVirtualenvDecoratedOperator(DecoratedOperator, PythonVirtualenvOperator):
    pass
