# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.decorators.base import DecoratedOperator
from airfly._vendor.airflow.operators.python import PythonOperator


@immutable
class _PythonDecoratedOperator(DecoratedOperator, PythonOperator):
    pass
