# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.transfers.adls_to_gcs import (
    ADLSToGCSOperator,
)


@immutable
class AdlsToGoogleCloudStorageOperator(ADLSToGCSOperator):
    pass
