# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.amazon.aws.operators.batch import AwsBatchOperator


@immutable
class AWSBatchOperator(AwsBatchOperator):
    pass
