# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.transfers.cassandra_to_gcs import (
    CassandraToGCSOperator,
)


@immutable
class CassandraToGoogleCloudStorageOperator(CassandraToGCSOperator):
    pass
