# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.operators.dataproc import (
    DataprocCreateClusterOperator,
    DataprocDeleteClusterOperator,
    DataprocInstantiateInlineWorkflowTemplateOperator,
    DataprocInstantiateWorkflowTemplateOperator,
    DataprocJobBaseOperator,
    DataprocScaleClusterOperator,
    DataprocSubmitHadoopJobOperator,
    DataprocSubmitHiveJobOperator,
    DataprocSubmitPigJobOperator,
    DataprocSubmitPySparkJobOperator,
    DataprocSubmitSparkJobOperator,
    DataprocSubmitSparkSqlJobOperator,
)


@immutable
class DataprocClusterCreateOperator(DataprocCreateClusterOperator):
    pass


@immutable
class DataprocClusterDeleteOperator(DataprocDeleteClusterOperator):
    pass


@immutable
class DataprocClusterScaleOperator(DataprocScaleClusterOperator):
    pass


@immutable
class DataProcHadoopOperator(DataprocSubmitHadoopJobOperator):
    pass


@immutable
class DataProcHiveOperator(DataprocSubmitHiveJobOperator):
    pass


@immutable
class DataProcJobBaseOperator(DataprocJobBaseOperator):
    pass


@immutable
class DataProcPigOperator(DataprocSubmitPigJobOperator):
    pass


@immutable
class DataProcPySparkOperator(DataprocSubmitPySparkJobOperator):
    pass


@immutable
class DataProcSparkOperator(DataprocSubmitSparkJobOperator):
    pass


@immutable
class DataProcSparkSqlOperator(DataprocSubmitSparkSqlJobOperator):
    pass


@immutable
class DataprocWorkflowTemplateInstantiateInlineOperator(
    DataprocInstantiateInlineWorkflowTemplateOperator
):
    pass


@immutable
class DataprocWorkflowTemplateInstantiateOperator(
    DataprocInstantiateWorkflowTemplateOperator
):
    pass
