# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.operators.dataflow import (
    DataflowCreateJavaJobOperator,
    DataflowCreatePythonJobOperator,
    DataflowTemplatedJobStartOperator,
)


@immutable
class DataFlowJavaOperator(DataflowCreateJavaJobOperator):
    pass


@immutable
class DataFlowPythonOperator(DataflowCreatePythonJobOperator):
    pass


@immutable
class DataflowTemplateOperator(DataflowTemplatedJobStartOperator):
    pass
