# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.transfers.local_to_gcs import (
    LocalFilesystemToGCSOperator,
)


@immutable
class FileToGoogleCloudStorageOperator(LocalFilesystemToGCSOperator):
    pass
