# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.operators.cloud_storage_transfer_service import (
    CloudDataTransferServiceCancelOperationOperator,
    CloudDataTransferServiceCreateJobOperator,
    CloudDataTransferServiceDeleteJobOperator,
    CloudDataTransferServiceGCSToGCSOperator,
    CloudDataTransferServiceGetOperationOperator,
    CloudDataTransferServiceListOperationsOperator,
    CloudDataTransferServicePauseOperationOperator,
    CloudDataTransferServiceResumeOperationOperator,
    CloudDataTransferServiceS3ToGCSOperator,
    CloudDataTransferServiceUpdateJobOperator,
)


@immutable
class GcpTransferServiceJobCreateOperator(CloudDataTransferServiceCreateJobOperator):
    pass


@immutable
class GcpTransferServiceJobDeleteOperator(CloudDataTransferServiceDeleteJobOperator):
    pass


@immutable
class GcpTransferServiceJobUpdateOperator(CloudDataTransferServiceUpdateJobOperator):
    pass


@immutable
class GcpTransferServiceOperationCancelOperator(
    CloudDataTransferServiceCancelOperationOperator
):
    pass


@immutable
class GcpTransferServiceOperationGetOperator(
    CloudDataTransferServiceGetOperationOperator
):
    pass


@immutable
class GcpTransferServiceOperationPauseOperator(
    CloudDataTransferServicePauseOperationOperator
):
    pass


@immutable
class GcpTransferServiceOperationResumeOperator(
    CloudDataTransferServiceResumeOperationOperator
):
    pass


@immutable
class GcpTransferServiceOperationsListOperator(
    CloudDataTransferServiceListOperationsOperator
):
    pass


@immutable
class GoogleCloudStorageToGoogleCloudStorageTransferOperator(
    CloudDataTransferServiceGCSToGCSOperator
):
    pass


@immutable
class S3ToGoogleCloudStorageTransferOperator(CloudDataTransferServiceS3ToGCSOperator):
    pass
