# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.operators.bigtable import (
    BigtableCreateInstanceOperator,
    BigtableCreateTableOperator,
    BigtableDeleteInstanceOperator,
    BigtableDeleteTableOperator,
    BigtableUpdateClusterOperator,
)
from airfly._vendor.airflow.providers.google.cloud.sensors.bigtable import (
    BigtableTableReplicationCompletedSensor,
)


@immutable
class BigtableClusterUpdateOperator(BigtableUpdateClusterOperator):
    pass


@immutable
class BigtableInstanceCreateOperator(BigtableCreateInstanceOperator):
    pass


@immutable
class BigtableInstanceDeleteOperator(BigtableDeleteInstanceOperator):
    pass


@immutable
class BigtableTableCreateOperator(BigtableCreateTableOperator):
    pass


@immutable
class BigtableTableDeleteOperator(BigtableDeleteTableOperator):
    pass


@immutable
class BigtableTableWaitForReplicationSensor(BigtableTableReplicationCompletedSensor):
    pass
