# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.operators.dlp import (
    CloudDLPDeleteDLPJobOperator,
    CloudDLPGetDLPJobOperator,
    CloudDLPGetDLPJobTriggerOperator,
    CloudDLPListDLPJobsOperator,
)


@immutable
class CloudDLPDeleteDlpJobOperator(CloudDLPDeleteDLPJobOperator):
    pass


@immutable
class CloudDLPGetDlpJobOperator(CloudDLPGetDLPJobOperator):
    pass


@immutable
class CloudDLPGetJobTripperOperator(CloudDLPGetDLPJobTriggerOperator):
    pass


@immutable
class CloudDLPListDlpJobsOperator(CloudDLPListDLPJobsOperator):
    pass
