# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.operators.text_to_speech import (
    CloudTextToSpeechSynthesizeOperator,
)


@immutable
class GcpTextToSpeechSynthesizeOperator(CloudTextToSpeechSynthesizeOperator):
    pass
