# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.operators.natural_language import (
    CloudNaturalLanguageAnalyzeEntitiesOperator,
    CloudNaturalLanguageAnalyzeEntitySentimentOperator,
    CloudNaturalLanguageAnalyzeSentimentOperator,
    CloudNaturalLanguageClassifyTextOperator,
)


@immutable
class CloudLanguageAnalyzeEntitiesOperator(CloudNaturalLanguageAnalyzeEntitiesOperator):
    pass


@immutable
class CloudLanguageAnalyzeEntitySentimentOperator(
    CloudNaturalLanguageAnalyzeEntitySentimentOperator
):
    pass


@immutable
class CloudLanguageAnalyzeSentimentOperator(
    CloudNaturalLanguageAnalyzeSentimentOperator
):
    pass


@immutable
class CloudLanguageClassifyTextOperator(CloudNaturalLanguageClassifyTextOperator):
    pass
