# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.operators.translate_speech import (
    CloudTranslateSpeechOperator,
)


@immutable
class GcpTranslateSpeechOperator(CloudTranslateSpeechOperator):
    pass
