# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.operators.cloud_sql import (
    CloudSQLBaseOperator,
    CloudSQLCreateInstanceDatabaseOperator,
    CloudSQLCreateInstanceOperator,
    CloudSQLDeleteInstanceDatabaseOperator,
    CloudSQLDeleteInstanceOperator,
    CloudSQLExecuteQueryOperator,
    CloudSQLExportInstanceOperator,
    CloudSQLImportInstanceOperator,
    CloudSQLInstancePatchOperator,
    CloudSQLPatchInstanceDatabaseOperator,
)


@immutable
class CloudSqlBaseOperator(CloudSQLBaseOperator):
    pass


@immutable
class CloudSqlInstanceCreateOperator(CloudSQLCreateInstanceOperator):
    pass


@immutable
class CloudSqlInstanceDatabaseCreateOperator(CloudSQLCreateInstanceDatabaseOperator):
    pass


@immutable
class CloudSqlInstanceDatabaseDeleteOperator(CloudSQLDeleteInstanceDatabaseOperator):
    pass


@immutable
class CloudSqlInstanceDatabasePatchOperator(CloudSQLPatchInstanceDatabaseOperator):
    pass


@immutable
class CloudSqlInstanceDeleteOperator(CloudSQLDeleteInstanceOperator):
    pass


@immutable
class CloudSqlInstanceExportOperator(CloudSQLExportInstanceOperator):
    pass


@immutable
class CloudSqlInstanceImportOperator(CloudSQLImportInstanceOperator):
    pass


@immutable
class CloudSqlInstancePatchOperator(CloudSQLInstancePatchOperator):
    pass


@immutable
class CloudSqlQueryOperator(CloudSQLExecuteQueryOperator):
    pass
