# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.operators.compute import (
    ComputeEngineBaseOperator,
    ComputeEngineCopyInstanceTemplateOperator,
    ComputeEngineInstanceGroupUpdateManagerTemplateOperator,
    ComputeEngineSetMachineTypeOperator,
    ComputeEngineStartInstanceOperator,
    ComputeEngineStopInstanceOperator,
)


@immutable
class GceBaseOperator(ComputeEngineBaseOperator):
    pass


@immutable
class GceInstanceGroupManagerUpdateTemplateOperator(
    ComputeEngineInstanceGroupUpdateManagerTemplateOperator
):
    pass


@immutable
class GceInstanceStartOperator(ComputeEngineStartInstanceOperator):
    pass


@immutable
class GceInstanceStopOperator(ComputeEngineStopInstanceOperator):
    pass


@immutable
class GceInstanceTemplateCopyOperator(ComputeEngineCopyInstanceTemplateOperator):
    pass


@immutable
class GceSetMachineTypeOperator(ComputeEngineSetMachineTypeOperator):
    pass
