# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.transfers.gcs_to_local import (
    GCSToLocalFilesystemOperator,
)


@immutable
class GoogleCloudStorageDownloadOperator(GCSToLocalFilesystemOperator):
    pass
