# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.transfers.mssql_to_gcs import (
    MSSQLToGCSOperator,
)


@immutable
class MsSqlToGoogleCloudStorageOperator(MSSQLToGCSOperator):
    pass
