# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.oracle.transfers.oracle_to_oracle import (
    OracleToOracleOperator,
)


@immutable
class OracleToOracleTransfer(OracleToOracleOperator):
    pass
