# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.transfers.postgres_to_gcs import (
    PostgresToGCSOperator,
)


@immutable
class PostgresToGoogleCloudStorageOperator(PostgresToGCSOperator):
    pass
