# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.transfers.sql_to_gcs import (
    BaseSQLToGCSOperator,
)


@immutable
class BaseSQLToGoogleCloudStorageOperator(BaseSQLToGCSOperator):
    pass
