# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.apache.hive.transfers.vertica_to_hive import (
    VerticaToHiveOperator,
)


@immutable
class VerticaToHiveTransfer(VerticaToHiveOperator):
    pass
