# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.mysql.transfers.vertica_to_mysql import (
    VerticaToMySqlOperator,
)


@immutable
class VerticaToMySqlTransfer(VerticaToMySqlOperator):
    pass
