# NOTE: This file is auto-generated by "inv sync-meta"


name = "airfly"
version = "0.9.0"
description = "Auto generate Airflow's dag.py on the fly"
authors = [{"name": "ryanchao2012", "email": "ryanchao2012@gmail.com"}]
readme = "README.md"
license = {"text": "MIT"}
dependencies = [
    "attrs",
    "cattrs",
    "regex",
    "networkx",
    "black",
    "isort",
    "click",
    "asttrs",
]
scripts = {"airfly": "airfly.cli.main:main"}
