# NOTE: This file is auto-generated by "inv sync-meta"

name = "airfly"
version = "0.2.0"
description = "Generate airflow's dag.py on the fly"
authors = ["ryanchao2012 <ryanchao2012@gmail.com>"]
license = "MIT"
