# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


@immutable
class MongoSensor(BaseSensorOperator):
    collection: "str"
    query: "dict"
    mongo_conn_id: "str"
