# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


@immutable
class QuboleSensor(BaseSensorOperator):
    data: "_empty"
    qubole_conn_id: "str"


@immutable
class QuboleFileSensor(QuboleSensor):
    pass


@immutable
class QubolePartitionSensor(QuboleSensor):
    pass
