# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


@immutable
class WebHdfsSensor(BaseSensorOperator):
    filepath: "str"
    webhdfs_conn_id: "str"
