# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


@immutable
class FTPSensor(BaseSensorOperator):
    path: "str"
    ftp_conn_id: "str"
    fail_on_transient_errors: "bool"


@immutable
class FTPSSensor(FTPSensor):
    path: "str"
    ftp_conn_id: "str"
    fail_on_transient_errors: "bool"
