# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


class RedisPubSubSensor(BaseSensorOperator):
    channels: "typing.Union[typing.List[str], str]"
    redis_conn_id: "str"
