# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


@immutable
class RedisKeySensor(BaseSensorOperator):
    key: "str"
    redis_conn_id: "str"
