# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class GCSToLocalFilesystemOperator(BaseOperator):
    bucket: "str"
    object_name: "str"
    filename: "str | None"
    store_to_xcom_key: "str | None"
    gcp_conn_id: "str"
    impersonation_chain: "str | Sequence[str] | None"
    file_encoding: "str"
