# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class LocalFilesystemToGCSOperator(BaseOperator):
    src: "_empty"
    dst: "_empty"
    bucket: "_empty"
    gcp_conn_id: "_empty"
    mime_type: "_empty"
    gzip: "_empty"
    chunk_size: "int | None"
    impersonation_chain: "str | Sequence[str] | None"
