# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.providers.google.cloud.transfers.sql_to_gcs import (
    BaseSQLToGCSOperator,
)


@immutable
class PostgresToGCSOperator(BaseSQLToGCSOperator):
    postgres_conn_id: "_empty"
    use_server_side_cursor: "_empty"
    cursor_itersize: "_empty"
