# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.operators.sql import SQLCheckOperator


@immutable
class DruidCheckOperator(SQLCheckOperator):
    druid_broker_conn_id: "str"
