# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


class HivePartitionSensor(BaseSensorOperator):
    table: "str"
    partition: "typing.Union[str, NoneType]"
    metastore_conn_id: "str"
    schema: "str"
    poke_interval: "int"
