# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.models.baseoperator import BaseOperator


@immutable
class OracleOperator(BaseOperator):
    sql: "str"
    oracle_conn_id: "str"
    parameters: "typing.Union[typing.Mapping, typing.Iterable, NoneType]"
    autocommit: "bool"
