# This file is auto-generated by airfly 0.6.0
from datetime import datetime

from airflow.models import DAG
from airflow.operators.bash import BashOperator
from airflow.operators.python import PythonOperator

from complex.catalog import _print_catalog

# >>>>>>>>>> Include from 'params.py'
dag_kwargs = dict(
    schedule_interval=None,
    start_date=datetime(2021, 1, 1),
    catchup=False,
    tags=["example", "example2", "example3"],
)
# <<<<<<<<<< End of code insertion
with DAG("example_complex", **dag_kwargs) as dag:
    complex_catalog_search_catalog = PythonOperator(
        task_id="complex.catalog.search_catalog", python_callable=_print_catalog
    )
    complex_catalog_search_catalog_result = BashOperator(
        task_id="complex.catalog.search_catalog_result",
        bash_command="echo search_catalog_result",
    )
    complex_entry_create_entry_gcs = BashOperator(
        task_id="complex.entry.create_entry_gcs", bash_command="echo create_entry_gcs"
    )
    complex_entry_create_entry_gcs_result = BashOperator(
        task_id="complex.entry.create_entry_gcs_result",
        bash_command="echo create_entry_gcs_result",
    )
    complex_entry_create_entry_gcs_result2 = BashOperator(
        task_id="complex.entry.create_entry_gcs_result2",
        bash_command="echo create_entry_gcs_result",
    )
    complex_entry_create_entry_group = BashOperator(
        task_id="complex.entry.create_entry_group",
        bash_command="echo create_entry_group",
    )
    complex_entry_create_entry_group_result = BashOperator(
        task_id="complex.entry.create_entry_group_result",
        bash_command="echo create_entry_group_result",
    )
    complex_entry_create_entry_group_result2 = BashOperator(
        task_id="complex.entry.create_entry_group_result2",
        bash_command="echo create_entry_group_result2",
    )
    complex_entry_delete_entry = BashOperator(
        task_id="complex.entry.delete_entry", bash_command="echo delete_entry"
    )
    complex_entry_delete_entry_group = BashOperator(
        task_id="complex.entry.delete_entry_group",
        bash_command="echo delete_entry_group",
    )
    complex_entry_get_entry = BashOperator(
        task_id="complex.entry.get_entry", bash_command="echo get_entry"
    )
    complex_entry_get_entry_group = BashOperator(
        task_id="complex.entry.get_entry_group", bash_command="echo get_entry_group"
    )
    complex_entry_get_entry_group_result = BashOperator(
        task_id="complex.entry.get_entry_group_result",
        bash_command="echo get_entry_group_result",
    )
    complex_entry_get_entry_result = BashOperator(
        task_id="complex.entry.get_entry_result", bash_command="echo get_entry_result"
    )
    complex_entry_lookup_entry = BashOperator(
        task_id="complex.entry.lookup_entry", bash_command="echo lookup_entry"
    )
    complex_entry_lookup_entry_result = BashOperator(
        task_id="complex.entry.lookup_entry_result",
        bash_command="echo lookup_entry_result",
    )
    complex_entry_update_entry = BashOperator(
        task_id="complex.entry.update_entry", bash_command="echo update_entry"
    )
    complex_tag_create_tag = BashOperator(
        task_id="complex.tag.create_tag", bash_command="echo create_tag"
    )
    complex_tag_create_tag_result = BashOperator(
        task_id="complex.tag.create_tag_result", bash_command="echo create_tag_result"
    )
    complex_tag_create_tag_result2 = BashOperator(
        task_id="complex.tag.create_tag_result2", bash_command="echo create_tag_result2"
    )
    complex_tag_create_tag_template = BashOperator(
        task_id="complex.tag.create_tag_template",
        bash_command="echo create_tag_template",
    )
    complex_tag_create_tag_template_field = BashOperator(
        task_id="complex.tag.create_tag_template_field",
        bash_command="echo create_tag_template_field",
    )
    complex_tag_create_tag_template_field_result = BashOperator(
        task_id="complex.tag.create_tag_template_field_result",
        bash_command="echo create_tag_template_field_result",
    )
    complex_tag_create_tag_template_field_result2 = BashOperator(
        task_id="complex.tag.create_tag_template_field_result2",
        bash_command="echo create_tag_template_field_result2",
    )
    complex_tag_create_tag_template_result = BashOperator(
        task_id="complex.tag.create_tag_template_result",
        bash_command="echo create_tag_template_result",
    )
    complex_tag_create_tag_template_result2 = BashOperator(
        task_id="complex.tag.create_tag_template_result2",
        bash_command="echo create_tag_template_result2",
    )
    complex_tag_delete_tag = BashOperator(
        task_id="complex.tag.delete_tag", bash_command="echo delete_tag"
    )
    complex_tag_delete_tag_template = BashOperator(
        task_id="complex.tag.delete_tag_template",
        bash_command="echo delete_tag_template",
    )
    complex_tag_delete_tag_template_field = BashOperator(
        task_id="complex.tag.delete_tag_template_field",
        bash_command="echo delete_tag_template_field",
    )
    complex_tag_get_tag_template = BashOperator(
        task_id="complex.tag.get_tag_template", bash_command="echo get_tag_template"
    )
    complex_tag_get_tag_template_result = BashOperator(
        task_id="complex.tag.get_tag_template_result",
        bash_command="echo get_tag_template_result",
    )
    complex_tag_list_tags = BashOperator(
        task_id="complex.tag.list_tags", bash_command="echo list_tags"
    )
    complex_tag_list_tags_result = BashOperator(
        task_id="complex.tag.list_tags_result", bash_command="echo list_tags_result"
    )
    complex_tag_rename_tag_template_field = BashOperator(
        task_id="complex.tag.rename_tag_template_field",
        bash_command="echo rename_tag_template_field",
    )
    complex_tag_update_tag = BashOperator(
        task_id="complex.tag.update_tag", bash_command="echo update_tag"
    )
    complex_tag_update_tag_template = BashOperator(
        task_id="complex.tag.update_tag_template",
        bash_command="echo update_tag_template",
    )
    complex_tag_update_tag_template_field = BashOperator(
        task_id="complex.tag.update_tag_template_field",
        bash_command="echo update_tag_template_field",
    )
    complex_catalog_search_catalog >> complex_catalog_search_catalog_result
    complex_catalog_search_catalog >> complex_entry_delete_entry
    complex_catalog_search_catalog >> complex_entry_delete_entry_group
    complex_catalog_search_catalog >> complex_tag_delete_tag
    complex_catalog_search_catalog >> complex_tag_delete_tag_template
    complex_catalog_search_catalog >> complex_tag_delete_tag_template_field
    complex_entry_create_entry_gcs >> complex_catalog_search_catalog
    complex_entry_create_entry_gcs >> complex_entry_create_entry_gcs_result
    complex_entry_create_entry_gcs >> complex_entry_create_entry_gcs_result2
    complex_entry_create_entry_gcs >> complex_entry_delete_entry
    complex_entry_create_entry_gcs >> complex_entry_get_entry
    complex_entry_create_entry_gcs >> complex_entry_lookup_entry
    complex_entry_create_entry_gcs >> complex_entry_update_entry
    complex_entry_create_entry_gcs >> complex_tag_create_tag_template
    complex_entry_create_entry_group >> complex_catalog_search_catalog
    complex_entry_create_entry_group >> complex_entry_create_entry_gcs
    complex_entry_create_entry_group >> complex_entry_create_entry_group_result
    complex_entry_create_entry_group >> complex_entry_create_entry_group_result2
    complex_entry_create_entry_group >> complex_entry_delete_entry_group
    complex_entry_delete_entry_group >> complex_entry_delete_entry
    complex_entry_get_entry >> complex_entry_delete_entry
    complex_entry_lookup_entry >> complex_entry_delete_entry
    complex_entry_lookup_entry >> complex_entry_lookup_entry_result
    complex_entry_update_entry >> complex_entry_delete_entry
    complex_tag_create_tag_template_field >> complex_catalog_search_catalog
    (
        complex_tag_create_tag_template_field
        >> complex_tag_create_tag_template_field_result
    )
    (
        complex_tag_create_tag_template_field
        >> complex_tag_create_tag_template_field_result2
    )
    complex_tag_create_tag_template_field >> complex_tag_delete_tag_template_field
    complex_tag_create_tag_template_field >> complex_tag_rename_tag_template_field
    complex_tag_create_tag_template_field >> complex_tag_update_tag_template_field
    complex_tag_create_tag_template >> complex_catalog_search_catalog
    complex_tag_create_tag_template >> complex_tag_create_tag_template_field
    complex_tag_create_tag_template >> complex_tag_create_tag_template_result
    complex_tag_create_tag_template >> complex_tag_create_tag_template_result2
    complex_tag_create_tag_template >> complex_tag_delete_tag_template_field
    complex_tag_create_tag_template >> complex_tag_get_tag_template
    complex_tag_create_tag_template >> complex_tag_update_tag_template
    complex_tag_create_tag >> complex_catalog_search_catalog
    complex_tag_create_tag >> complex_tag_delete_tag
    complex_tag_create_tag >> complex_tag_list_tags
    complex_tag_delete_tag_template_field >> complex_tag_delete_tag_template
    complex_tag_delete_tag_template >> complex_entry_delete_entry_group
    complex_tag_delete_tag >> complex_tag_delete_tag_template_field
    complex_tag_get_tag_template >> complex_tag_delete_tag_template
    complex_tag_get_tag_template >> complex_tag_get_tag_template_result
    complex_tag_list_tags >> complex_tag_delete_tag
    complex_tag_list_tags >> complex_tag_list_tags_result
    complex_tag_rename_tag_template_field >> complex_tag_delete_tag_template_field
    complex_tag_update_tag_template_field >> complex_tag_rename_tag_template_field
    complex_tag_update_tag_template >> complex_tag_delete_tag_template
