# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class GlueJobOperator(BaseOperator):
    job_name: "str"
    job_desc: "str"
    script_location: "str | None"
    concurrent_run_limit: "int | None"
    script_args: "dict | None"
    retry_limit: "int"
    num_of_dpus: "int | float | None"
    aws_conn_id: "str | None"
    region_name: "str | None"
    s3_bucket: "str | None"
    iam_role_name: "str | None"
    iam_role_arn: "str | None"
    create_job_kwargs: "dict | None"
    run_job_kwargs: "dict | None"
    wait_for_completion: "bool"
    deferrable: "bool"
    verbose: "bool"
    update_config: "bool"
    job_poll_interval: "int | float"
    stop_job_run_on_kill: "bool"
