# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class GlueCrawlerOperator(BaseOperator):
    config: "_empty"
    aws_conn_id: "_empty"
    region_name: "str | None"
    poll_interval: "int"
    wait_for_completion: "bool"
    deferrable: "bool"
