# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.models.baseoperator import BaseOperator


@immutable
class SnsPublishOperator(BaseOperator):
    target_arn: "str"
    message: "str"
    aws_conn_id: "str"
    subject: "typing.Union[str, NoneType]"
    message_attributes: "typing.Union[dict, NoneType]"
