# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.operators.dummy import DummyOperator


@immutable
class DummySkipOperator(DummyOperator):
    pass
