# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class VerticaToMySqlOperator(BaseOperator):
    sql: "str"
    mysql_table: "str"
    vertica_conn_id: "str"
    mysql_conn_id: "str"
    mysql_preoperator: "str | None"
    mysql_postoperator: "str | None"
    bulk_load: "bool"
