# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator
from airfly._vendor.airflow.models.skipmixin import SkipMixin


class BaseSensorOperator(BaseOperator, SkipMixin):
    poke_interval: "float"
    timeout: "float"
    soft_fail: "bool"
    mode: "str"
    exponential_backoff: "bool"
