# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


@immutable
class BashSensor(BaseSensorOperator):
    bash_command: "_empty"
    env: "_empty"
    output_encoding: "_empty"
