# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


class DateTimeSensor(BaseSensorOperator):
    target_time: "str | datetime.datetime"


class DateTimeSensorAsync(DateTimeSensor):
    start_from_trigger: "bool"
    end_from_trigger: "bool"
    trigger_kwargs: "dict[str, Any] | None"
