# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


@immutable
class DateTimeSensor(BaseSensorOperator):
    target_time: "typing.Union[str, datetime.datetime]"
