# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


@immutable
class TimeSensor(BaseSensorOperator):
    target_time: "_empty"
