# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


@immutable
class DayOfWeekSensor(BaseSensorOperator):
    week_day: "_empty"
    use_task_execution_day: "_empty"
