# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


@immutable
class CassandraRecordSensor(BaseSensorOperator):
    table: "str"
    keys: "typing.Dict[str, str]"
    cassandra_conn_id: "str"
