# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


class CassandraRecordSensor(BaseSensorOperator):
    keys: "dict[str, str]"
    table: "str"
    cassandra_conn_id: "str"
