# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.sensors.base import BaseSensorOperator


@immutable
class CassandraTableSensor(BaseSensorOperator):
    table: "str"
    cassandra_conn_id: "str"
