# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class S3ToTeradataOperator(BaseOperator):
    s3_source_key: "str"
    public_bucket: "bool"
    teradata_table: "str"
    aws_conn_id: "str"
    teradata_conn_id: "str"
    teradata_authorization_name: "str"
