# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class RedshiftToS3Operator(BaseOperator):
    s3_bucket: "str"
    s3_key: "str"
    schema: "str | None"
    table: "str | None"
    select_query: "str | None"
    redshift_conn_id: "str"
    aws_conn_id: "str | None"
    verify: "bool | str | None"
    unload_options: "list | None"
    autocommit: "bool"
    include_header: "bool"
    parameters: "Iterable | Mapping | None"
    table_as_file_name: "bool"
    redshift_data_api_kwargs: "dict | None"
