# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class JiraOperator(BaseOperator):
    jira_method: "str"
    jira_conn_id: "str"
    jira_method_args: "dict | None"
    result_processor: "Callable | None"
    get_jira_resource_method: "Callable | None"
