# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class MSGraphAsyncOperator(BaseOperator):
    url: "str"
    response_type: "ResponseType | None"
    path_parameters: "dict[str, Any] | None"
    url_template: "str | None"
    method: "str"
    query_parameters: "dict[str, QueryParams] | None"
    headers: "dict[str, str] | None"
    data: "dict[str, Any] | str | BytesIO | None"
    conn_id: "str"
    key: "str"
    timeout: "float | None"
    proxies: "dict | None"
    api_version: "APIVersion | None"
    pagination_function: (
        "Callable[[MSGraphAsyncOperator, dict], tuple[str, dict]] | None"
    )
    result_processor: "Callable[[Context, Any], Any]"
    serializer: "type[ResponseSerializer]"
