# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class AzureSynapseRunSparkBatchOperator(BaseOperator):
    azure_synapse_conn_id: "str"
    wait_for_termination: "bool"
    spark_pool: "str"
    payload: "SparkBatchJobOptions"
    timeout: "int"
    check_interval: "int"


class AzureSynapseRunPipelineOperator(BaseOperator):
    pipeline_name: "str"
    azure_synapse_conn_id: "str"
    azure_synapse_workspace_dev_endpoint: "str"
    wait_for_termination: "bool"
    reference_pipeline_run_id: "str | None"
    is_recovery: "bool | None"
    start_activity_name: "str | None"
    parameters: "dict[str, Any] | None"
    timeout: "int"
    check_interval: "int"
