# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.models.baseoperator import BaseOperator


@immutable
class RedisPublishOperator(BaseOperator):
    channel: "str"
    message: "str"
    redis_conn_id: "str"
