# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class GCSToGoogleDriveOperator(BaseOperator):
    source_bucket: "str"
    source_object: "str"
    destination_object: "str | None"
    destination_folder_id: "str"
    move_object: "bool"
    gcp_conn_id: "str"
    impersonation_chain: "str | Sequence[str] | None"
    delegate_to: "str | None"
