# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class MsSqlToHiveOperator(BaseOperator):
    sql: "str"
    hive_table: "str"
    create: "bool"
    recreate: "bool"
    partition: "dict | None"
    delimiter: "str"
    mssql_conn_id: "str"
    hive_cli_conn_id: "str"
    hive_auth: "str | None"
    tblproperties: "dict | None"
