# Auto generated by 'inv collect-airflow'
from airfly._vendor.airflow.models.baseoperator import BaseOperator


class S3ToHiveOperator(BaseOperator):
    s3_key: "str"
    field_dict: "dict"
    hive_table: "str"
    delimiter: "str"
    create: "bool"
    recreate: "bool"
    partition: "dict | None"
    headers: "bool"
    check_headers: "bool"
    wildcard_match: "bool"
    aws_conn_id: "str | None"
    verify: "bool | str | None"
    hive_cli_conn_id: "str"
    input_compressed: "bool"
    tblproperties: "dict | None"
    select_expression: "str | None"
    hive_auth: "str | None"
