# Auto generated by 'inv collect-airflow'
from airfly._ast import immutable
from airfly._vendor.airflow.models.baseoperator import BaseOperator


@immutable
class QuboleOperator(BaseOperator):
    qubole_conn_id: "str"
